import Head from 'next/head';
import React from 'react';
import Cta from '../../components/Cta';
import Div from '../../components/Div';
import Layout from '../../components/Layout';
import PageHeading from '../../components/PageHeading';
import SectionHeading from '../../components/SectionHeading';
import Spacing from '../../components/Spacing';
import Team from '../../components/Team';

export default function TeamPage() {
  const teamData = [
    {
      memberImage: '/images/koushik.jpg',
      memberName: 'Koushik Avula',
      memberDesignation: 'Director',
      memberSocial: {
        
      },
      
    },
    {
      memberImage: '/images/sujith.jpg',
      memberName: 'Sujith Chereddy',
      memberDesignation: 'Director',
      memberSocial: {
        
      },     
    },
    {
      memberImage: '/images/mounisha.jpg',
      memberName: 'Mounisha',
      memberDesignation: 'HR',
      memberSocial: {
        
      },     
    },
    
    
    {
      memberImage: '/images/bhavya.jpg',
      memberName: 'Bhavya Konda',
      memberDesignation: 'Strategist',
      memberSocial: {
       
      },
    },
    {
    memberImage: '/images/husain.jpg',
    memberName: 'Husain Naqvi',
    memberDesignation: 'Graphic Designer',
    memberSocial: {
     
    },
  },
  {
    memberImage: '/images/gajanand.jpg',
    memberName: 'Ghajanand',
    memberDesignation: 'Graphic Designer',
    memberSocial: {
      
    },
  },
  {
    memberImage: '/images/pranati.jpg',
    memberName: 'Pranati Bhadrachalam',
    memberDesignation: 'CSM',
    memberSocial: {
      
    },
  },
  {
    memberImage: '/images/vishal.jpg',
    memberName: 'Vishal Bharadwaj',
    memberDesignation: 'Sr Developer',
    memberSocial: {
      
    },
  },
  {
    memberImage: '/images/praveen.jpg',
    memberName: 'Praveen K',
    memberDesignation: 'App Tester',
    memberSocial: {
      
    },
  },
  {
    memberImage: '/images/dilip.jpg',
    memberName: 'Dileep K',
    memberDesignation: 'Lead Analyst',
    memberSocial: {
     
    },
  },
  {
    memberImage: '/images/nidhi.jpg',
    memberName: 'Nidhi Reddy',
    memberDesignation: 'Sr Analyst',
    memberSocial: {
      
    },
  },
  {
    memberImage: '/images/swetha.jpg',
    memberName: 'Swetha Guntupalli ',
    memberDesignation: 'Full Stack Developer',
    memberSocial: {
      
    },
  },
  {
    memberImage: '/images/harika1.jpg',
    memberName: 'Harika Nidadavolu',
    memberDesignation: 'Business Operations Manager',
    memberSocial: {
      
    },
  },
  {
    memberImage: '/images/sanjay.jpg',
    memberName: 'Sanjay Korukonda',
    memberDesignation: 'Business Operations Manager',
    memberSocial: {
      
    },
  },
  {
    memberImage: '/images/saha.jpg',
    memberName: 'Satya Harika',
    memberDesignation: 'Private Equity Associate',
    memberSocial: {
      
    },
  },
  {
    memberImage: '/images/karthik.jpg',
    memberName: 'Karthikeya Reddy Chilla',
    memberDesignation: 'Client Relation Manager',
    memberSocial: {
      
    },
  },
    
    
  ];
  return (
    <>
      <Head>
        <title>Team</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Our Team"
          bgSrc="images/team_hero_bg.jpeg"
          pageLinkText="Team"
        />
        <Spacing lg="145" md="80" />
        <Div className="container">
          <SectionHeading
            title="Meet our awesome <br/>team members"
            subtitle="Our Team"
            variant="cs-style1 text-center"
          />
          <Spacing lg="90" md="45" />
          <Div className="row">
            {teamData.map((item, index) => (
              <Div key={index} className="col-lg-3 col-sm-6">
                <Team
                  memberImage={item.memberImage}
                  memberName={item.memberName}
                  memberDesignation={item.memberDesignation}
                  memberSocial={item.memberSocial}
                />
                <Spacing lg="80" md="30" />
              </Div>
            ))}
          </Div>
          <Spacing lg="70" md="50" />
          <Div className="container">
            <Cta
              title="Let’s disscuse make <br />something <i>cool</i> together"
              btnText="Apply For Meeting"
              btnLink="/contact"
              bgSrc="/images/cta_bg.jpeg"
            />
          </Div>
        </Div>
      </Layout>
    </>
  );
}
